# Generated by Django 3.0.1 on 2020-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultydetail', '0002_section_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_code', models.IntegerField()),
                ('depart_name', models.TextField()),
                ('shortform', models.CharField(default=' ', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='extendeduserfaculty',
            name='Department',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduserfaculty',
            name='Section',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduserfaculty',
            name='Year',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=40)),
                ('depart_enrolled', models.ManyToManyField(to='facultydetail.department')),
                ('section_enrolled', models.ManyToManyField(to='facultydetail.section')),
                ('year_enrolled', models.ManyToManyField(to='facultydetail.year')),
            ],
        ),
    ]
