# Generated by Django 3.0.1 on 2020-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultydetail', '0003_auto_20200508_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sec',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10),
        ),
    ]
