# Generated by Django 3.0.1 on 2020-05-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultydetail', '0004_auto_20200508_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='year_enrolled',
        ),
        migrations.DeleteModel(
            name='year',
        ),
    ]
