# Generated by Django 3.0.1 on 2020-05-09 13:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facultydetail', '0005_auto_20200509_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', multiselectfield.db.fields.MultiSelectField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=15)),
            ],
        ),
    ]
